name: supabase
description: A Supabase client.
environment:
  sdk: ^2.0.0-alpha.144
dependencies:
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.15.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.7.0
