name: supabase
description: A Supabase client.
environment:
  sdk: ^2.0.0-alpha.128
dependencies:
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.13.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.3.4
