-- Copyright (C) 2023 Toitware ApS. All rights reserved.

INSERT INTO filters (data, value, valuef, b, int_array, dates)
  VALUES
    ('abc', null, null, null, null, null),
    (E'\'', null, null, null, null, null),
    ('"', null, null, null, null, null),
    ('\', null, null, null, null, null),
    ('\"', null, null, null, null, null),
    ('\\', null, null, null, null, null),
    ('""', null, null, null, null, null),
    ('foobar', null, null, null, null, null),
    ('foo"bar', null, null, null, null, null),
    ('null', null, null, null, null, null),
    (null, -1, null, null, null, null),
    (null, 0, null, null, null, null),
    (null, 1, null, null, null, null),
    (null, 2, null, null, null, null),
    (null, 3, null, null, null, null),
    (null, 4, null, null, null, null),
    (null, 5, null, null, null, null),
    (null, 6, null, null, null, null),
    (null, 7, null, null, null, null),
    (null, 8, null, null, null, null),
    (null, null, -1.1, null, null, null),
    (null, null, 0.0, null, null, null),
    (null, null, 1.1, null, null, null),
    (null, null, 2.2, null, null, null),
    (null, null, 3.3, null, null, null),
    (null, null, 4.4, null, null, null),
    (null, null, 5.5, null, null, null),
    (null, null, 6.6, null, null, null),
    (null, null, 7.7, null, null, null),
    (null, null, 8.8, null, null, null),
    (null, null, null, false, null, null),
    (null, null, null, true, null, null),
    (null, null, null, null, ARRAY[1, 2, 3], null),
    (null, null, null, null, ARRAY[11, 22, 33, 44], null),
    (null, null, null, null, null, '2023-07-27T13:37:21.000000+00:00'),
    (null, null, null, null, null, '1997-05-02T19:12:34.567891+00:00')
;
