# Copyright (C) 2023 Toitware ApS. All rights reserved.

name: CI

on:
  push:

env:
  EXCLUDED_SUPABASE_SERVICES: imgproxy,inbucket,pgadmin-schema-diff,migra,studio,deno-relay,edge-runtime

jobs:
  build:
    strategy:
      matrix:
        # The versions should contain (at least) the lowest requirement
        #    and a version that is more up to date.
        toit-version: [ v2.0.0-alpha.128, latest ]
        include:
          - toit-version: v2.0.0-alpha.128
            version-name: old
          - toit-version: latest
            version-name: new

    name: CI - ubuntu-latest - ${{ matrix.version-name }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: toitlang/action-setup@v1
        with:
          toit-version: ${{ matrix.toit-version }}

      - name: Install Supabase
        uses: supabase/setup-cli@v1
        with:
          version: 1.82.2

      - name: Start Supabase
        shell: bash
        working-directory: ${{ github.workspace }}/tests/supabase/supabase_test
        run: |
          supabase start -x "$EXCLUDED_SUPABASE_SERVICES"
          supabase status

      - name: Test
        run: |
          make test
